task: xstest
dataset_path: data/raw/xstest
output_type: generate_until
test_split: test
doc_to_text: "{{prompt}}"
doc_to_target: "{{type}}"
generation_kwargs:
  max_gen_toks: 100
  until:
    - "\n\n"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true